openapi: 3.0.0
info:
  description: "Gatekeeper & Load Balancer for On Demand Media Streaming "
  version: 1.0.0
  title: Heimdall
tags:
  - name: alive
    description: Health check
  - name: image
    description: Access to image resources
  - name: document
    description: Access to document resources
paths:
  /alive:
    get:
      tags:
        - alive
      summary: Heath check API endpoint that returns the health of Heimdall.
      responses:
        "200":
          description: Heimdall is up and running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
  /image/transcode:
    get:
      tags:
        - image
      summary: Convert image from the given identifier to JPEG format with the suitable quality for viewing.
      parameters:
        - name: evidence_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the Evidence
          required: true
          example: 038903efb824496682cda85830f423bd
        - name: partner_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the Partner/Agency
          required: true
          example: b98219c8e1da4028ab39f57cf9314168
        - name: file_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the File.
          required: true
          example: c4511c2933e346fda7e2f21ac8cf1077
        - name: AXONSESSION
          in: cookie
          schema:
            type: string
          description: You can login to your agency and copy this value for faster testing
          required: true
          example: vp6cbgahaqc4n6zdcnrzk5wrakcrvxdbuq9o96ugr9c9fmf7h
      responses:
        "200":
          $ref: '#/components/responses/ImageOK'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'
  /image/zoom:
    get:
      tags:
        - image
      summary: Convert image from the given identifier to JPEG format with the suitable quality for zooming.
      parameters:
        - name: evidence_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the Evidence
          required: true
          example: 038903efb824496682cda85830f423bd
        - name: partner_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the Partner/Agency
          required: true
          example: b98219c8e1da4028ab39f57cf9314168
        - name: file_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the File.
          required: true
          example: c4511c2933e346fda7e2f21ac8cf1077
        - name: AXONSESSION
          in: cookie
          schema:
            type: string
          description: You can login to your agency and copy this value for faster testing
          required: true
          example: vp6cbgahaqc4n6zdcnrzk5wrakcrvxdbuq9o96ugr9c9fmf7h
      responses:
        "200":
          $ref: '#/components/responses/ImageOK'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'
  /image/metadata:
    get:
      tags:
        - image
      summary: Retrieve EXIF metadata with given identifier of image
      parameters:
        - name: evidence_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the Evidence
          required: true
          example: 038903efb824496682cda85830f423bd
        - name: partner_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the Partner/Agency
          required: true
          example: b98219c8e1da4028ab39f57cf9314168
        - name: file_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the File.
          required: true
          example: c4511c2933e346fda7e2f21ac8cf1077
        - name: AXONSESSION
          in: cookie
          schema:
            type: string
            format: uuid
          description: You can login to your agency and copy this value for faster testing
          required: true
          example: vp6cbgahaqc4n6zdcnrzk5wrakcrvxdbuq9o96ugr9c9fmf7h
      responses:
        "200":
          $ref: '#/components/responses/MetadataOK'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'
  /document/view:
    get:
      tags:
        - document
      summary: Retrieve document resources
      parameters:
        - name: evidence_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the Evidence
          required: true
          example: 038903efb824496682cda85830f423bd
        - name: partner_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the Partner/Agency
          required: true
          example: b98219c8e1da4028ab39f57cf9314168
        - name: file_id
          in: query
          schema:
            type: string
            format: uuid
          description: The unique UUID identifying the File.
          required: true
          example: c4511c2933e346fda7e2f21ac8cf1077
        - name: AXONSESSION
          in: cookie
          schema:
            type: string
            format: uuid
          description: You can login to your agency and copy this value for faster testing
          required: true
          example: vp6cbgahaqc4n6zdcnrzk5wrakcrvxdbuq9o96ugr9c9fmf7h
      responses:
        "200":
          $ref: '#/components/responses/DocumentOK'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "500":
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    ImageOK:
      description: Successfully retrieve image
      headers:
        Content-Length:
          schema:
            type: integer
          description: The Content-Length entity header indicates the size of the entity-body, in bytes, sent to the recipient.
      content:
        image/jpeg:
          schema:
            type: string
            format: binary
    MetadataOK:
      description: Successfully retrieve image's metadata
      headers:
        Content-Length:
          schema:
            type: integer
          description: The Content-Length entity header indicates the size of the entity-body, in bytes, sent to the recipient.
      content:
        application/json:
          examples:
            json:
              value: '{"dateTime": {"displayName": "Modified Date", "displayValue": "2013:11:27 09:21:07"},"software": {"displayName": "Software","displayValue": "Ver.1.00 "}}'
    DocumentOK:
      description: Successfully retrieve documents
      headers:
        Content-Length:
          schema:
            type: integer
          description: The Content-Length entity header indicates the size of the entity-body, in bytes, sent to the recipient.
      content:
        application/pdf:
          schema:
            type: string
            format: binary
    Unauthorized:
      description: Unauthorized. The request requires authentication.
    InternalServerError:
      description: Internal Server Error. You should never receive this error but if you are unlucky enough to get one, please report it to us.

servers: [
{
  url: "https://sb-pro.qa.evidence.com/api/v1/media",
  description: QA (DV1) environment
},
{
  url: "https://evp.ag1.evidence.com/api/v1/media",
  description: QA (AG1) environment
}
]
